# Local variables:
# after-save-hook: org-html-export-to-html
# end:

#+BEGIN_SRC emacs-lisp :export no
(defun org-mode-export-myfile ()
  "Export org document to HTML automatically on change"
  (when (equal (buffer-file-name) "/path/to/links.org")
    (progn
      (org-html-export-to-html)
      (message "HTML exported"))))

(add-hook 'after-save-hook 'org-mode-export-myfile)
#+END_SRC


* Intro

This course and the book constitute an high speed overview of the most important fundamental computer science areas. It is intended for intermediate and professional developers who, for any reason, are interested in getting to know the formal, academic side of CS better.

The goal is to provide an overview deep enough so that you end up understanding the ares, their problems and the connections between them. And shallow enough so that you aren't buried under hundreds of pages of proofs, formalizations and exercises.

We will start by trying to understand what computer science is and why it isn't a new area at all. We'll consider the computability as a fundamental property of reality rather than a technological apparatus.

We shall then proceed to learning essential mathematics necessary for further topics. These include proof techniques, notation and logic.

Next, we will learn about the following topics:

#+BEGIN_EXPORT latex
\marginnote{This is a margin note using the geometry package, set at 3cm vertical offset to the line it is typeseted.}
#+END_EXPORT

1. Algorithms. Complexity and examples of important algorithms in sorting.
1. Abstract Data Types.
1. Set theory.
1. Graph theory.
1. Theory of computation.
1. Cryptography.
1. Information theory.

Since it seems impossible or at least unpractical to put all of computer science curriculum into a single course, even in a minified format, we shall leave the following topics for the last chapter. In it, we will give an overview to them:

- Abstract algebra
- Category theory
- Type theory
- Computational geometry

* Foundations of Math

** Set theory

*** Intro to sets

Set theory is an important area of math which lays as a foundation of many computer science topics, such as databases, types in programming. Set theory isn't difficult conceptually, and is generally nice to think about, especially if you're a visual learner.

A set is simply a collection of things. A thing can be anything: name, object, idea. It's a very abstract notion.

For example, I can define a set of movies I have seen: American Pie, Breakfast Club, The Room. Yes, I have only seen those three movies in my entire life. I am busy writing computer science books.

Actually, I've watched The Room five times. Does this affect the set? No, because it doesn't change the notion of "what movies have I watched". This obvious thing is an integral property of sets: they include unique objects.

#+BEGIN_EXPORT latex
\marginnote{Nothing stops us from defining a set of movie viewings, though.}
#+END_EXPORT

If an object $o$ is in set $A$, we say $o$ is a member of $A$. To express this fact easily, mathematicians use the following notation: $o \in A$.

So, if $o$ is "The Room", and $A$ is "Movies I've watched", then $o \in A$. But if $b$ is "Avengers", and I haven't watched Avengers, then $b \notin A$.

If we were to look inside set $A$, it might look like this:

\begin{equation}
\{s, m, o\}
\end{equation}

Since $b \notin A$, we can't find $b$ among the members.

Sets don't have the notion of order, so it doesn't matter how you mention its members as long as you mention them all. So, all these:

- $\{s, m, o\}$
- $\{s, o, m\}$
- $\{m, s, o\}$
- etc.

describe the same set $A$.

Here we were lucky: set $A$ is finite and quite small. But sets can be infinite, and it would be impossible to write all its members. There are ways to describe such sets nevertheless. For example, the set of all natural numbers from 1 to n can be described like so:

\begin{equation}
\{1, 2, 3, 4, ... n\}
\end{equation}



*** Empty set

Mathematicians love zero. Ever since its inception around 1770 BC, zero is an important part of mathematical models. The notion of "nothingness", which zero reflects in the context of counting, is present in all areas. In the context of sets, nothingness is an /empty set/.

Obviously, an empty set is a set without members.

\begin{equation}
\{\}
\end{equation}

Why would we need empty sets? Well, sometimes we want to describe a notion of having no objects under a certain description. For example, since I only watched 3 movies in my life, and all of them were American, I can describe a set of all non-American movies I've watched: it's an empty set $Z = \{\}$.


*** Subset, superset

When all members of set $A$ are present in another set $B$, then $A$ is a subset of $B$. This notion is expressed like so:

\begin{equation}
A \subseteq B
\end{equation}

Let's say set $B$ is the set of all movies ever produced. Then $A$ is clearly a subset of $B$.

To look at things from the other end, $B$ is a superset of $A$:

\begin{equation}
B \supseteq A
\end{equation}

You know what else is a subset of $B$? An empty set!

\begin{equation}
\{\} \subseteq B
\end{equation}

This either sounds absolutely natural to you or extremely weird. This makes perfect sense to a mathematician, because it's easy to argue: /all/ members of $\{\}$ are present in $B$, all zero of them.

It gets weirder. As per our definition, if all members of a set are also present in another set, then the one is a subset of the other. This means any set is a subset of itself.

\begin{equation}
A \subseteq A \\
B \subseteq B \\
Z \subseteq B
\end{equation}

By extension, if two sets are the same, then any of them is a subset of the other.

Since often we only care about cases where sets aren't equal, there's a special notion of a *proper subset*.

If $A$ is a subset of $B$, but $A$ is not equal to $B$, then $A$ is a proper subset of $B$.

\begin{equation}
A \subset B
\end{equation}

So, a set if a subset of itself, but is never a proper subset of itself.

*** Maps

Sets are somewhat boring.
